# Generated by Django 4.2 on 2023-04-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_customtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomToken",
        ),
    ]
