# Generated by Django 4.1.7 on 2023-04-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
