# Generated by Django 4.2 on 2023-04-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_pages", "0002_rename_category_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="product_pics"),
        ),
    ]
